# Generated by Django 4.1.2 on 2022-10-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('tipodocumento', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Libreta Civica', 'Libreta Civica')], max_length=50, null=True)),
                ('numdocumento', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
