# Generated by Django 3.0 on 2022-10-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
    ]
