# Generated by Django 3.0 on 2022-10-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora', '0003_auto_20221023_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
