# Generated by Django 4.1.2 on 2022-10-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultora', '0006_auto_20221023_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='numdocumento',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='tipodocumento',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.documento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='postulanteidioma',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='postulanteidioma',
            name='estado',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.estado', verbose_name='ID estado'),
        ),
        migrations.AlterField(
            model_name='postulanteidioma',
            name='idioma',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.idioma', verbose_name='ID idioma'),
        ),
        migrations.AlterField(
            model_name='postulanteidioma',
            name='postulante',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.postulante', verbose_name='ID Postulante'),
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=250, verbose_name='Razon Social')),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('barrio', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.barrio')),
                ('tipoorganizacion', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.tipoorganizacion', verbose_name='Tipo de Organizacion')),
            ],
        ),
    ]
