# Generated by Django 4.1.2 on 2022-10-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultora', '0007_tipoorganizacion_alter_documento_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaApertura', models.DateField(blank=True, null=True)),
                ('fechaCierre', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.estado')),
                ('idioma', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.idioma', verbose_name='ID idioma')),
                ('organizacion', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultora.organizacion', verbose_name='Id Organizacion')),
            ],
        ),
        
    ]
