# Generated by Django 4.1.2 on 2022-10-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultora', '0008_busquedalaboral_busquedalaboraltecnologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedalaboral',
            name='tecnologia',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='consultora.tecnologia'),
        ),
    ]
